use Biblioteca

select * from Moneda

insert into Moneda(Symbol, Name) values ('AED','Arabes Unidos (Emiratos) - Dirham')
insert into Moneda(Symbol, Name) values ('AFN','Afgani Afgano') 
insert into Moneda(Symbol, Name) values ('ALL','Lek Albanés')
insert into Moneda(Symbol, Name) values ('AMD','Dram armenio')
insert into Moneda(Symbol, Name) values ('ANG','Florín antillano neerlandés')
insert into Moneda(Symbol, Name) values ('AOA','Kwanza angoleño')
insert into Moneda(Symbol, Name) values ('ARS','Peso argentino')
insert into Moneda(Symbol, Name) values ('AUD','Dólar australiano')
insert into Moneda(Symbol, Name) values ('AWG','Florín arubeño')
insert into Moneda(Symbol, Name) values ('AZM','Manat azerbaiyano')
insert into Moneda(Symbol, Name) values ('BAM','Marco convertible de Bosnia-Herzegovina')
insert into Moneda(Symbol, Name) values ('BBD','Dólar de Barbados')
insert into Moneda(Symbol, Name) values ('BDT','Taka de Bangladesh')
insert into Moneda(Symbol, Name) values ('BGN','Lev búlgaro')
insert into Moneda(Symbol, Name) values ('BHD','Dinar bahreiní')
insert into Moneda(Symbol, Name) values ('BIF','Franco burundés')
insert into Moneda(Symbol, Name) values ('BMD','Dólar de Bermuda')
insert into Moneda(Symbol, Name) values ('BND','Dólar de Brunéi')
insert into Moneda(Symbol, Name) values ('BOB','Boliviano')
insert into Moneda(Symbol, Name) values ('BOV','Mvdol boliviano')
insert into Moneda(Symbol, Name) values ('BRL','Real brasileño')
insert into Moneda(Symbol, Name) values ('BSD','Dólar bahameño')
insert into Moneda(Symbol, Name) values ('BTN','Ngultrum de Bután')
insert into Moneda(Symbol, Name) values ('BWP','Pula de Botsuana')
insert into Moneda(Symbol, Name) values ('BYR','Rublo bielorruso')
insert into Moneda(Symbol, Name) values ('BZD','Dólar de Belice')
insert into Moneda(Symbol, Name) values ('CAD','Dólar canadiense')
insert into Moneda(Symbol, Name) values ('CDF','Franco congoleño')
insert into Moneda(Symbol, Name) values ('CHF','Franco suizo')
insert into Moneda(Symbol, Name) values ('CLF','Unidades de fomento chilenas')
insert into Moneda(Symbol, Name) values ('CLP','Peso chileno')	
insert into Moneda(Symbol, Name) values ('CNY','Yuan Renminbi de China')
insert into Moneda(Symbol, Name) values ('COP','Peso colombiano')
insert into Moneda(Symbol, Name) values ('COU','Unidad de valor real colombiana')							
insert into Moneda(Symbol, Name) values ('CRC','Colón costarricense')
insert into Moneda(Symbol, Name) values ('CUP','Peso cubano')
insert into Moneda(Symbol, Name) values ('CUC','Peso cubano convertible')
insert into Moneda(Symbol, Name) values ('CVE','Escudo caboverdiano')
insert into Moneda(Symbol, Name) values ('CYP','Libra chipriota')
insert into Moneda(Symbol, Name) values ('CZK','Corona checa')
insert into Moneda(Symbol, Name) values ('DJF','Franco yibutiano')
insert into Moneda(Symbol, Name) values ('DKK','Corona danesa')
insert into Moneda(Symbol, Name) values ('DOP','Peso dominicano')
insert into Moneda(Symbol, Name) values ('DZD','Dinar argelino')
insert into Moneda(Symbol, Name) values ('EEK','Corona estonia')
insert into Moneda(Symbol, Name) values ('EGP','Libra egipcia')
insert into Moneda(Symbol, Name) values ('ERN','Nakfa eritreo')
insert into Moneda(Symbol, Name) values ('ETB','Birr etíope')
insert into Moneda(Symbol, Name) values ('EUR','Euro')
insert into Moneda(Symbol, Name) values ('FJD','Dólar fiyiano')
insert into Moneda(Symbol, Name) values ('FKP','Libra malvinense')
insert into Moneda(Symbol, Name) values ('GBP','Libra esterlina')
insert into Moneda(Symbol, Name) values ('GEL','Lari georgiano')
insert into Moneda(Symbol, Name) values ('GHS','Cedi ghanés')
insert into Moneda(Symbol, Name) values ('GIP','Libra de Gibraltar')
insert into Moneda(Symbol, Name) values ('GMD','Dalasi gambiano')
insert into Moneda(Symbol, Name) values ('GNF','Franco guineano')
insert into Moneda(Symbol, Name) values ('GTQ','Quetzal guatemalteco')
insert into Moneda(Symbol, Name) values ('GYD','Dólar guyanés')
insert into Moneda(Symbol, Name) values ('HKD','Dólar de Hong Kong')
insert into Moneda(Symbol, Name) values ('HNL','Lempira hondureño')
insert into Moneda(Symbol, Name) values ('HRK','Kuna croata')
insert into Moneda(Symbol, Name) values ('HTG','Gourde haitiano')
insert into Moneda(Symbol, Name) values ('HUF','Forint húngaro')
insert into Moneda(Symbol, Name) values ('IDR','Rupiah indonesia')
insert into Moneda(Symbol, Name) values ('ILS','Nuevo shéquel israelí')
insert into Moneda(Symbol, Name) values ('INR','Rupia india')
insert into Moneda(Symbol, Name) values ('IQD','Dinar iraquí')
insert into Moneda(Symbol, Name) values ('IRR','Rial iraní')
insert into Moneda(Symbol, Name) values ('ISK','Corona islandesa')
insert into Moneda(Symbol, Name) values ('JMD','Dólar jamaicano')
insert into Moneda(Symbol, Name) values ('JOD','Dinar jordano')
insert into Moneda(Symbol, Name) values ('JPY','Yen japonés')
insert into Moneda(Symbol, Name) values ('KES','Chelín keniano')
insert into Moneda(Symbol, Name) values ('KGS','Som Kirguistán')
insert into Moneda(Symbol, Name) values ('KHR','Riel camboyano')
insert into Moneda(Symbol, Name) values ('KMF','Franco comoriano')
insert into Moneda(Symbol, Name) values ('KPW','Won norcoreano')
insert into Moneda(Symbol, Name) values ('KRW','Won surcoreano')
insert into Moneda(Symbol, Name) values ('KWD','Dinar kuwaití')
insert into Moneda(Symbol, Name) values ('KYD','Dólar caimano')
insert into Moneda(Symbol, Name) values ('KZT','Tenge kazajo')
insert into Moneda(Symbol, Name) values ('LAK','Kip laosiano')
insert into Moneda(Symbol, Name) values ('LBP','Libra libanesa')
insert into Moneda(Symbol, Name) values ('LKR','Rupia de Sri Lanka')
insert into Moneda(Symbol, Name) values ('LRD','Dólar liberiano')
insert into Moneda(Symbol, Name) values ('LSL','Loti lesotense')
insert into Moneda(Symbol, Name) values ('LTL','Litas lituana')
insert into Moneda(Symbol, Name) values ('LVL','Lats letón')
insert into Moneda(Symbol, Name) values ('LYD','Dinar libio')
insert into Moneda(Symbol, Name) values ('MAD','Dirham marroquí')
insert into Moneda(Symbol, Name) values ('MDL','Leu moldavo')
insert into Moneda(Symbol, Name) values ('MGA','Ariary malgache')
insert into Moneda(Symbol, Name) values ('MKD','Denar macedonio')
insert into Moneda(Symbol, Name) values ('MMK','Kyat birmano')
insert into Moneda(Symbol, Name) values ('MNT','Tugrik mongol')
insert into Moneda(Symbol, Name) values ('MOP','Pataca de Macao')
insert into Moneda(Symbol, Name) values ('MRO','Ouguiya mauritana')
insert into Moneda(Symbol, Name) values ('MTL','Lira maltesa')
insert into Moneda(Symbol, Name) values ('MUR','Rupia mauricia')
insert into Moneda(Symbol, Name) values ('MVR','Rupia de las Maldivas')
insert into Moneda(Symbol, Name) values ('MWK','Kwacha malauí')
insert into Moneda(Symbol, Name) values ('MXN','Peso mexicano')
insert into Moneda(Symbol, Name) values ('MYR','Ringgit malayo')
insert into Moneda(Symbol, Name) values ('MZN','Metical mozambiqueño')
insert into Moneda(Symbol, Name) values ('NAD','Dólar namibio')
insert into Moneda(Symbol, Name) values ('NGN','Naira nigeriano')
insert into Moneda(Symbol, Name) values ('NIO','Córdoba nicaragüense')
insert into Moneda(Symbol, Name) values ('NOK','Corona noruega')
insert into Moneda(Symbol, Name) values ('NPR','Rupia nepalesa')
insert into Moneda(Symbol, Name) values ('NZD','Dólar neozelandés')
insert into Moneda(Symbol, Name) values ('OMR','Rial omaní')
insert into Moneda(Symbol, Name) values ('PAB','Balboa panameño')
insert into Moneda(Symbol, Name) values ('PEN','Nuevo sol peruano')
insert into Moneda(Symbol, Name) values ('PGK','Kina de Papúa Nueva Guinea')
insert into Moneda(Symbol, Name) values ('PHP','Peso filipino')
insert into Moneda(Symbol, Name) values ('PKR','Rupia pakistaní')
insert into Moneda(Symbol, Name) values ('PLN','zloty polaco')
insert into Moneda(Symbol, Name) values ('PYG','Guaraní paraguayo')
insert into Moneda(Symbol, Name) values ('QAR','Riyal qatarí')
insert into Moneda(Symbol, Name) values ('RON','Leu rumano')
insert into Moneda(Symbol, Name) values ('RSD','Dinar serbio')
insert into Moneda(Symbol, Name) values ('RUB','Rublo ruso')
insert into Moneda(Symbol, Name) values ('RWF','Franco ruandés')
insert into Moneda(Symbol, Name) values ('SAR','Riyal saudí')
insert into Moneda(Symbol, Name) values ('SBD','Dólar de las Islas Salomón')
insert into Moneda(Symbol, Name) values ('SCR','Rupia de Seychelles')
insert into Moneda(Symbol, Name) values ('SDG','Dinar sudanés')
insert into Moneda(Symbol, Name) values ('SEK','Corona sueca')
insert into Moneda(Symbol, Name) values ('SGD','Dólar de Singapur')
insert into Moneda(Symbol, Name) values ('SHP','Libra de Santa Helena')
insert into Moneda(Symbol, Name) values ('SKK','Corona eslovaca')
insert into Moneda(Symbol, Name) values ('SLL','Leone de Sierra Leona')
insert into Moneda(Symbol, Name) values ('SOS','Chelín somalí')
insert into Moneda(Symbol, Name) values ('SRD','Dólar surinamés')
insert into Moneda(Symbol, Name) values ('STD','Dobra de Santo Tomé y Príncipe')
insert into Moneda(Symbol, Name) values ('SYP','Libra siria')
insert into Moneda(Symbol, Name) values ('SZL','Lilangeni suazi')
insert into Moneda(Symbol, Name) values ('THB','Baht tailandés')
insert into Moneda(Symbol, Name) values ('TJS','Somoni Tayikistán')
insert into Moneda(Symbol, Name) values ('TMT','Manat turcomano')
insert into Moneda(Symbol, Name) values ('TND','Dinar tunecino')
insert into Moneda(Symbol, Name) values ('TOP','Pa anga tongano')
insert into Moneda(Symbol, Name) values ('TRY','Lira turca')
insert into Moneda(Symbol, Name) values ('TTD','Dólar de Trinidad y Tobago')
insert into Moneda(Symbol, Name) values ('TWD','Dólar taiwanés')
insert into Moneda(Symbol, Name) values ('TZS','Chelín tanzano')
insert into Moneda(Symbol, Name) values ('UAH','Grivna ucraniana')
insert into Moneda(Symbol, Name) values ('UGX','Chelín ugandés')
insert into Moneda(Symbol, Name) values ('USD','Dólar estadounidense')
insert into Moneda(Symbol, Name) values ('UYU','Peso uruguayo')
insert into Moneda(Symbol, Name) values ('UZS','Som uzbeko')
insert into Moneda(Symbol, Name) values ('VEF','Bolívar fuerte venezolano')
insert into Moneda(Symbol, Name) values ('VND','Dong vietnamita')
insert into Moneda(Symbol, Name) values ('VUV','Vatu vanuatense')
insert into Moneda(Symbol, Name) values ('WST','Tala samoana')
insert into Moneda(Symbol, Name) values ('XAF','Franco CFA de África Central')
insert into Moneda(Symbol, Name) values ('XAG','Onza de plata')
insert into Moneda(Symbol, Name) values ('XAU','Onza de oro')
insert into Moneda(Symbol, Name) values ('XCD','Dólar del Caribe Oriental')
insert into Moneda(Symbol, Name) values ('XDR','Derechos Especiales de Giro')
insert into Moneda(Symbol, Name) values ('XFO','Franco de oro')
insert into Moneda(Symbol, Name) values ('XFU','Franco UIC')
insert into Moneda(Symbol, Name) values ('XOF','Franco CFA de África Occidental')
insert into Moneda(Symbol, Name) values ('XPD','Onza de paladio')
insert into Moneda(Symbol, Name) values ('XPF','Franco CFP')
insert into Moneda(Symbol, Name) values ('XPT','Onza de platino')
insert into Moneda(Symbol, Name) values ('XTS','Reservado para pruebas')
insert into Moneda(Symbol, Name) values ('XXX','Sin divisa')
insert into Moneda(Symbol, Name) values ('YER','Rial yemení')
insert into Moneda(Symbol, Name) values ('ZAR','Rand sudafricano')
insert into Moneda(Symbol, Name) values ('ZMK','Kwacha zambiano')
insert into Moneda(Symbol, Name) values ('ZWL','Dólar zimbabuense')

select * from Pais

insert into Pais(ID, Symbol, Name) values ('1','AF','Afganistán')
insert into Pais(ID, Symbol, Name) values ('2','AL','Albania')
insert into Pais(ID, Symbol, Name) values ('3','DZ','Algeria')
insert into Pais(ID, Symbol, Name) values ('4','AS','American Samoa')
insert into Pais(ID, Symbol, Name) values ('5','AD','Andorra')
insert into Pais(ID, Symbol, Name) values ('6','AO','Angola')
insert into Pais(ID, Symbol, Name) values ('7','AI','Anguila')
insert into Pais(ID, Symbol, Name) values ('8','AQ','Antartica')
insert into Pais(ID, Symbol, Name) values ('9','AG','Antigua y Barbuda')
insert into Pais(ID, Symbol, Name) values ('10','AR','Argentina')
insert into Pais(ID, Symbol, Name) values ('11','AM','Armenia')
insert into Pais(ID, Symbol, Name) values ('12','AW','Aruba')
insert into Pais(ID, Symbol, Name) values ('13','AU','Australia')
insert into Pais(ID, Symbol, Name) values ('14','AT','Austria')
insert into Pais(ID, Symbol, Name) values ('15','AZ','Azerbaiyán')
insert into Pais(ID, Symbol, Name) values ('16','BS','Bahamas')
insert into Pais(ID, Symbol, Name) values ('17','BH','Bahrein')
insert into Pais(ID, Symbol, Name) values ('18','BD','Bangladesh')
insert into Pais(ID, Symbol, Name) values ('19','BB','Barbados')
insert into Pais(ID, Symbol, Name) values ('20','BE','Bélgica')
insert into Pais(ID, Symbol, Name) values ('21','BZ','Belice')
insert into Pais(ID, Symbol, Name) values ('22','BJ','Benin')
insert into Pais(ID, Symbol, Name) values ('23','BM','Bermudas')
insert into Pais(ID, Symbol, Name) values ('24','BT','Bhután')
insert into Pais(ID, Symbol, Name) values ('25','BO','Bolivia')
insert into Pais(ID, Symbol, Name) values ('26','BA','Bosnia y Herzegovina')
insert into Pais(ID, Symbol, Name) values ('27','BW','Botswana')
insert into Pais(ID, Symbol, Name) values ('28','BV','Bouvet')
insert into Pais(ID, Symbol, Name) values ('29','BR','Brasil')
insert into Pais(ID, Symbol, Name) values ('30','IO','Británico del Océano Índico')
insert into Pais(ID, Symbol, Name) values ('31','VG','Islas Vírgenes Británicas')
insert into Pais(ID, Symbol, Name) values ('32','BN','Brunei Darussalam')
insert into Pais(ID, Symbol, Name) values ('33','BG','Bulgaria')
insert into Pais(ID, Symbol, Name) values ('34','BF','Burkina Faso')
insert into Pais(ID, Symbol, Name) values ('35','BI','Burundi')
insert into Pais(ID, Symbol, Name) values ('36','BY','Belarús')
insert into Pais(ID, Symbol, Name) values ('37','KH','Camboya')
insert into Pais(ID, Symbol, Name) values ('38','CM','Camerún')
insert into Pais(ID, Symbol, Name) values ('39','CA','Canadá')
insert into Pais(ID, Symbol, Name) values ('40','CV','Cabo Verde ')
insert into Pais(ID, Symbol, Name) values ('41','KY','Cayman Islands')
insert into Pais(ID, Symbol, Name) values ('42','CF','Central African Republic')
insert into Pais(ID, Symbol, Name) values ('43','TD','Chad')
insert into Pais(ID, Symbol, Name) values ('44','CL','Chile')
insert into Pais(ID, Symbol, Name) values ('45','CN','China')
insert into Pais(ID, Symbol, Name) values ('46','CX','Christmas Island')
insert into Pais(ID, Symbol, Name) values ('47','CC','Cocos Islands')
insert into Pais(ID, Symbol, Name) values ('48','CO','Colombia')
insert into Pais(ID, Symbol, Name) values ('49','KM','Comoros')
insert into Pais(ID, Symbol, Name) values ('50','CG','Congo')
insert into Pais(ID, Symbol, Name) values ('51','CK','Cook Islands')
insert into Pais(ID, Symbol, Name) values ('52','CR','Costa Rica')
insert into Pais(ID, Symbol, Name) values ('53','CI','Costa de Marfil')
insert into Pais(ID, Symbol, Name) values ('54','HR','Croacia')
insert into Pais(ID, Symbol, Name) values ('55','CU','Cuba')
insert into Pais(ID, Symbol, Name) values ('56','CY','Chipre')
insert into Pais(ID, Symbol, Name) values ('57','CZ','Checa Republica')
insert into Pais(ID, Symbol, Name) values ('58','KP','Corea Republica Popular')
insert into Pais(ID, Symbol, Name) values ('59','DK','Dinamarca')
insert into Pais(ID, Symbol, Name) values ('60','DJ','Djibouti')
insert into Pais(ID, Symbol, Name) values ('61','DM','Dominica')
insert into Pais(ID, Symbol, Name) values ('62','DO','Dominican Republic')
insert into Pais(ID, Symbol, Name) values ('63','TP','East Timor')
insert into Pais(ID, Symbol, Name) values ('64','EC','Ecuador')
insert into Pais(ID, Symbol, Name) values ('65','EG','Egypt')
insert into Pais(ID, Symbol, Name) values ('66','SV','El Salvador')
insert into Pais(ID, Symbol, Name) values ('67','GQ','Equatorial guinea')
insert into Pais(ID, Symbol, Name) values ('68','ER','Eritrea')
insert into Pais(ID, Symbol, Name) values ('69','EE','Estonia')
insert into Pais(ID, Symbol, Name) values ('70','ET','Ethiopia')
insert into Pais(ID, Symbol, Name) values ('71','FK','Falkland Islands')
insert into Pais(ID, Symbol, Name) values ('72','FO','Faroe Islands')
insert into Pais(ID, Symbol, Name) values ('73','FE','Federal Republic og Germany')
insert into Pais(ID, Symbol, Name) values ('74','FJ','Fiji')
insert into Pais(ID, Symbol, Name) values ('75','FI','Finland')
insert into Pais(ID, Symbol, Name) values ('76','FR','France')
insert into Pais(ID, Symbol, Name) values ('77','FX','France Metropolitan')
insert into Pais(ID, Symbol, Name) values ('78','GF','French Guiana')
insert into Pais(ID, Symbol, Name) values ('79','PF','French Polynesia')
insert into Pais(ID, Symbol, Name) values ('80','TF','French Southern Territories')
insert into Pais(ID, Symbol, Name) values ('81','GA','Gabon')
insert into Pais(ID, Symbol, Name) values ('82','GM','Gambia')
insert into Pais(ID, Symbol, Name) values ('83','GE','Georgia')
insert into Pais(ID, Symbol, Name) values ('84','GH','Ghana')
insert into Pais(ID, Symbol, Name) values ('85','GI','Gibraltar')
insert into Pais(ID, Symbol, Name) values ('86','GR','Greece')
insert into Pais(ID, Symbol, Name) values ('87','GL','Greenland')
insert into Pais(ID, Symbol, Name) values ('88','GD','Grenada')
insert into Pais(ID, Symbol, Name) values ('89','GP','Guadaloupe')
insert into Pais(ID, Symbol, Name) values ('90','GU','Guam')
insert into Pais(ID, Symbol, Name) values ('91','GT','Guatemala')
insert into Pais(ID, Symbol, Name) values ('92','GN','Guinea')
insert into Pais(ID, Symbol, Name) values ('93','GW','Guinea-Bissau')
insert into Pais(ID, Symbol, Name) values ('94','GY','Guyana')
insert into Pais(ID, Symbol, Name) values ('95','HT','Haiti')
insert into Pais(ID, Symbol, Name) values ('96','HM','Heard and Mcdonald Islands')
insert into Pais(ID, Symbol, Name) values ('97','HN','Honduras')
insert into Pais(ID, Symbol, Name) values ('98','HK','Hong-Kong')
insert into Pais(ID, Symbol, Name) values ('99','HU','Hungary')
insert into Pais(ID, Symbol, Name) values ('100','IS','Iceland')
insert into Pais(ID, Symbol, Name) values ('101','IN','India')
insert into Pais(ID, Symbol, Name) values ('102','ID','Indonesia')
insert into Pais(ID, Symbol, Name) values ('103','IR','Iran')
insert into Pais(ID, Symbol, Name) values ('104','IQ','Iraq')
insert into Pais(ID, Symbol, Name) values ('105','IE','Ireland')
insert into Pais(ID, Symbol, Name) values ('106','IL','Israel')
insert into Pais(ID, Symbol, Name) values ('107','IT','Italy')
insert into Pais(ID, Symbol, Name) values ('108','JM','Jamaica')
insert into Pais(ID, Symbol, Name) values ('109','JP','Japan')
insert into Pais(ID, Symbol, Name) values ('110','JO','Jordan')
insert into Pais(ID, Symbol, Name) values ('111','KZ','Kazakhstan')
insert into Pais(ID, Symbol, Name) values ('112','KE','Kenya')
insert into Pais(ID, Symbol, Name) values ('113','KI','Kiribati')
insert into Pais(ID, Symbol, Name) values ('114','KW','Kuwait')
insert into Pais(ID, Symbol, Name) values ('115','KG','Kyrgyzstan')
insert into Pais(ID, Symbol, Name) values ('116','LA','Lao Democratic Republic')
insert into Pais(ID, Symbol, Name) values ('117','LV','Latvia')
insert into Pais(ID, Symbol, Name) values ('118','LB','Lebanon')
insert into Pais(ID, Symbol, Name) values ('119','LS','Lesotho')
insert into Pais(ID, Symbol, Name) values ('120','LR','Liberia')
insert into Pais(ID, Symbol, Name) values ('121','LY','Libyan Arab')
insert into Pais(ID, Symbol, Name) values ('122','LI','Liechtenstein')
insert into Pais(ID, Symbol, Name) values ('123','LT','Lithuania')
insert into Pais(ID, Symbol, Name) values ('124','LU','Luxembourg')
insert into Pais(ID, Symbol, Name) values ('125','MO','Macao')
insert into Pais(ID, Symbol, Name) values ('126','MG','Madagascar')
insert into Pais(ID, Symbol, Name) values ('127','MW','Malawi')
insert into Pais(ID, Symbol, Name) values ('128','MY','Malasia')
insert into Pais(ID, Symbol, Name) values ('129','MV','Maldives')
insert into Pais(ID, Symbol, Name) values ('130','ML','Mali')
insert into Pais(ID, Symbol, Name) values ('131','MT','Malta')
insert into Pais(ID, Symbol, Name) values ('132','MH','Marshall Islands')
insert into Pais(ID, Symbol, Name) values ('133','MQ','Martinique')
insert into Pais(ID, Symbol, Name) values ('134','MR','Mauritania')
insert into Pais(ID, Symbol, Name) values ('135','MU','Mauritius')
insert into Pais(ID, Symbol, Name) values ('136','YT','Mayotte')
insert into Pais(ID, Symbol, Name) values ('137','MX','Mexico')
insert into Pais(ID, Symbol, Name) values ('138','FM','Micronesia')
insert into Pais(ID, Symbol, Name) values ('139','MD','Moldova')
insert into Pais(ID, Symbol, Name) values ('140','MC','Monaco')
insert into Pais(ID, Symbol, Name) values ('141','MN','Mongolia')
insert into Pais(ID, Symbol, Name) values ('142','MS','Montserrat')
insert into Pais(ID, Symbol, Name) values ('143','MA','Morocco')
insert into Pais(ID, Symbol, Name) values ('144','MZ','Mozambique')
insert into Pais(ID, Symbol, Name) values ('145','MM','Myanmar')
insert into Pais(ID, Symbol, Name) values ('146','NA','Namibia')
insert into Pais(ID, Symbol, Name) values ('147','NR','Nauru')
insert into Pais(ID, Symbol, Name) values ('148','NP','Nepal')
insert into Pais(ID, Symbol, Name) values ('149','NL','Netherlands')
insert into Pais(ID, Symbol, Name) values ('150','AN','Netherlands Antilles')
insert into Pais(ID, Symbol, Name) values ('151','NC','New Caledonia')
insert into Pais(ID, Symbol, Name) values ('152','NZ','New Zealand')
insert into Pais(ID, Symbol, Name) values ('153','NI','Nicaragua')
insert into Pais(ID, Symbol, Name) values ('154','NE','Niger')
insert into Pais(ID, Symbol, Name) values ('155','NG','Nigeria')
insert into Pais(ID, Symbol, Name) values ('156','NU','Niue')
insert into Pais(ID, Symbol, Name) values ('157','NF','Norfolk Island')
insert into Pais(ID, Symbol, Name) values ('158','MP','Northern Mariana Islands')
insert into Pais(ID, Symbol, Name) values ('159','NO','Norway')
insert into Pais(ID, Symbol, Name) values ('160','OM','Oman')
insert into Pais(ID, Symbol, Name) values ('161','PK','Pakistan')
insert into Pais(ID, Symbol, Name) values ('162','PW','Palau')
insert into Pais(ID, Symbol, Name) values ('163','PA','Panama')
insert into Pais(ID, Symbol, Name) values ('164','PG','Papua New Guinea')
insert into Pais(ID, Symbol, Name) values ('165','PY','Paraguay')
insert into Pais(ID, Symbol, Name) values ('166','PE','Peru')
insert into Pais(ID, Symbol, Name) values ('167','PH','Philippines')
insert into Pais(ID, Symbol, Name) values ('168','PN','Pitcairn')
insert into Pais(ID, Symbol, Name) values ('169','PL','Poland')
insert into Pais(ID, Symbol, Name) values ('170','PT','Portugal')
insert into Pais(ID, Symbol, Name) values ('171','PR','Puerto Rico')
insert into Pais(ID, Symbol, Name) values ('172','QA','Qatar')
insert into Pais(ID, Symbol, Name) values ('173','KR','Republic of Korea')
insert into Pais(ID, Symbol, Name) values ('174','RE','Reunion')
insert into Pais(ID, Symbol, Name) values ('175','RO','Romania')
insert into Pais(ID, Symbol, Name) values ('176','RU','Russian Federation')
insert into Pais(ID, Symbol, Name) values ('177','RW','Rwanda')
insert into Pais(ID, Symbol, Name) values ('178','KN','Saint Kitts and Nevis')
insert into Pais(ID, Symbol, Name) values ('179','LC','Saint Lucia')
insert into Pais(ID, Symbol, Name) values ('180','WS','Samoa')
insert into Pais(ID, Symbol, Name) values ('181','SM','San Marino')
insert into Pais(ID, Symbol, Name) values ('182','ST','Sao Tome and Principe')
insert into Pais(ID, Symbol, Name) values ('183','SA','Saudi Arabia')
insert into Pais(ID, Symbol, Name) values ('184','SN','Senegal')
insert into Pais(ID, Symbol, Name) values ('185','SC','Seychelles')
insert into Pais(ID, Symbol, Name) values ('186','SL','Sierra Leone')
insert into Pais(ID, Symbol, Name) values ('187','SG','Singapore')
insert into Pais(ID, Symbol, Name) values ('188','SK','Slovak Republic')
insert into Pais(ID, Symbol, Name) values ('189','SI','Slovenia')
insert into Pais(ID, Symbol, Name) values ('190','SB','Solomon Islands')
insert into Pais(ID, Symbol, Name) values ('191','SO','Somalia')
insert into Pais(ID, Symbol, Name) values ('192','ZA','South Africa')
insert into Pais(ID, Symbol, Name) values ('193','GS','South Georgia')
insert into Pais(ID, Symbol, Name) values ('194','ES','Spain')
insert into Pais(ID, Symbol, Name) values ('195','LK','Sri Lanka')
insert into Pais(ID, Symbol, Name) values ('196','SH','St. Helena')
insert into Pais(ID, Symbol, Name) values ('197','PM','St. Pierre and Miquelon')
insert into Pais(ID, Symbol, Name) values ('198','VC','St. Vincent and The Grenadines')
insert into Pais(ID, Symbol, Name) values ('199','SD','Sudan')
insert into Pais(ID, Symbol, Name) values ('200','SR','Suriname')
insert into Pais(ID, Symbol, Name) values ('201','SJ','Svalbard and Jan Mayen Islands')
insert into Pais(ID, Symbol, Name) values ('202','SZ','Swaziland')
insert into Pais(ID, Symbol, Name) values ('203','SE','Sweden')
insert into Pais(ID, Symbol, Name) values ('204','CH','Switzerland')
insert into Pais(ID, Symbol, Name) values ('205','SY','Syrian Arab')
insert into Pais(ID, Symbol, Name) values ('206','TW','Taiwan')
insert into Pais(ID, Symbol, Name) values ('207','TJ','Tajikistan')
insert into Pais(ID, Symbol, Name) values ('208','TH','Thailand')
insert into Pais(ID, Symbol, Name) values ('209','TG','Togo')
insert into Pais(ID, Symbol, Name) values ('210','TK','Tokelau')
insert into Pais(ID, Symbol, Name) values ('211','TO','Tonga')
insert into Pais(ID, Symbol, Name) values ('212','TT','Trinidad and Tobago')
insert into Pais(ID, Symbol, Name) values ('213','TN','Tunisia')
insert into Pais(ID, Symbol, Name) values ('214','TR','Turkey')
insert into Pais(ID, Symbol, Name) values ('215','TM','Turkmenistan')
insert into Pais(ID, Symbol, Name) values ('216','TC','Turks and Caicos Islands')
insert into Pais(ID, Symbol, Name) values ('217','TV','Tuvalu')
insert into Pais(ID, Symbol, Name) values ('218','UG','Uganda')
insert into Pais(ID, Symbol, Name) values ('219','UA','Ukraine')
insert into Pais(ID, Symbol, Name) values ('220','AE','United Arab Emirates')
insert into Pais(ID, Symbol, Name) values ('221','GB','United Kingdom')
insert into Pais(ID, Symbol, Name) values ('222','TZ','United Republic of Tanzania')
insert into Pais(ID, Symbol, Name) values ('223','US','United States')
insert into Pais(ID, Symbol, Name) values ('224','UM','United States Minor Islands')
insert into Pais(ID, Symbol, Name) values ('225','VI','United States Virgin Islands')
insert into Pais(ID, Symbol, Name) values ('226','UY','Uruguay')
insert into Pais(ID, Symbol, Name) values ('227','UZ','Uzbekistan')
insert into Pais(ID, Symbol, Name) values ('228','VU','Vanuatu')
insert into Pais(ID, Symbol, Name) values ('229','VA','Vatican City State')
insert into Pais(ID, Symbol, Name) values ('230','VE','Venezuela')
insert into Pais(ID, Symbol, Name) values ('231','VN','Vietnam')
insert into Pais(ID, Symbol, Name) values ('232','WF','Wallis and Futuna Islands')
insert into Pais(ID, Symbol, Name) values ('233','EH','Western Sahara')
insert into Pais(ID, Symbol, Name) values ('234','YE','Yemen')
insert into Pais(ID, Symbol, Name) values ('235','YU','Yugoslavia')
insert into Pais(ID, Symbol, Name) values ('236','ZR','Zaire')
insert into Pais(ID, Symbol, Name) values ('237','ZM','Zambia')
insert into Pais(ID, Symbol, Name) values ('238','ZW','Zimbabwe')

drop table Pais